import type { Metadata } from 'next'
import './globals.css'
import Providers from '@/lib/theme/Providers/Providers'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
     <Providers>
     <html lang="en">
      <body className="font-Montserrat">
      <AppRouterCacheProvider>
        {children}
        </AppRouterCacheProvider>
      </body>
    </html>
    </Providers>
  )
}
